services:
  - type: web
    name: linkdin
    env: python
    buildCommand: pip install -r requirements.txt && playwright install --with-deps chromium
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
